spring.application.name=feedlink-backend

# Database Configuration (PostgreSQL NeonDB)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-sparkling-morning-ao90u3i9-pooler.c-2.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_I5cHy4sVJxfM}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Security Configuration
jwt.secret=${JWT_SECRET:verylongandcomplexsecretkeythatshouldbeatleast32characterslong}
jwt.expiration=86400000

# Server Configuration
server.port=8080
